import type { CaseStatus } from "@prisma/client";

export const STATUS_LABELS: Record<CaseStatus, string> = {
  IMPORTADO: "Importado",
  PENDENTE_DISPARO: "Pendente de disparo",
  PROCESSANDO_DISPARO: "Processando disparo",
  MENSAGEM_ENVIADA: "Mensagem enviada",
  MENSAGEM_ENTREGUE: "Mensagem entregue",
  MENSAGEM_LIDA: "Mensagem lida",
  AGUARDANDO_RESPOSTA: "Aguardando resposta",
  CLIENTE_RESPONDEU: "Cliente respondeu",
  ENDERECO_CONFIRMADO: "Endereço confirmado",
  ENDERECO_DIVERGENTE: "Endereço divergente",
  ATENDIMENTO_HUMANO: "Atendimento humano",
  EM_ATENDIMENTO: "Em atendimento",
  AGUARDANDO_AGENDAMENTO: "Aguardando agendamento",
  AGENDADO: "Agendado",
  AGUARDANDO_ROTA: "Aguardando rota",
  ROTA_PLANEJADA: "Rota planejada",
  ATRIBUIDO_MOTOBOY: "Atribuído a motoboy",
  EM_DESLOCAMENTO: "Em deslocamento",
  EQUIPAMENTO_RETIRADO: "Equipamento retirado",
  RETIRADA_NAO_REALIZADA: "Retirada não realizada",
  CLIENTE_AUSENTE: "Cliente ausente",
  ENDERECO_NAO_LOCALIZADO: "Endereço não localizado",
  CLIENTE_RECUSOU: "Cliente recusou",
  CONTATO_INVALIDO: "Contato inválido",
  CANCELADO: "Cancelado",
  CLIENTE_RETIDO: "Cliente retido",
  AGUARDANDO_BAIXA: "Aguardando baixa",
  BAIXA_PROCESSANDO: "Baixa processando",
  BAIXA_REALIZADA: "Baixa realizada",
  ERRO_BAIXA: "Erro na baixa",
  FINALIZADO: "Finalizado",
};
